Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -55,10 +55,10 @@ jobs:
           docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest ls -la /
           
           echo "Checking if entrypoint.sh exists and is executable..."
-          docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest test -x /entrypoint.sh && echo "Entrypoint exists and is executable" || echo "Entrypoint NOT found or NOT executable"
+          docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest test -x entrypoint.sh && echo "Entrypoint exists and is executable" || echo "Entrypoint NOT found or NOT executable"
           
           echo "Checking entrypoint.sh content (if it exists)..."
-          docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest cat /entrypoint.sh || echo "Could not read entrypoint.sh"
+          docker run --rm ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest cat entrypoint.sh || echo "Could not read entrypoint.sh"
 
 
       - name: Push Docker image to Artifact Registry
